name: techtest
description: Simple app to support the Flutter recruitment
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path_provider: ^2.0.12
  retrofit: ^4.0.1
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.9.1
  mocktail: ^1.0.4
  netsells_flutter_analysis: ^5.0.0
  retrofit_generator: ^9.1.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/